name: Deploy Micro Frontend to GitHub Pages

on:
  push:
    branches: [ main, master ]
    paths:
      - 'shell/**'
      - 'counter/**'
      - 'todos/**'
      - 'ui-kit/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      run: pnpm install

    - name: Build UI Kit
      run: |
        cd ui-kit
        pnpm build

    - name: Build Counter App
      run: |
        cd counter
        pnpm build
      env:
        NODE_ENV: production

    - name: Build Todos App
      run: |
        cd todos
        pnpm build
      env:
        NODE_ENV: production

    - name: Build Shell App
      run: |
        cd shell
        pnpm build
      env:
        NODE_ENV: production
        GITHUB_PAGES: true

    - name: Setup GitHub Pages
      run: |
        # 创建部署目录结构
        mkdir -p deploy

        # 复制 shell 应用到根目录
        cp -r shell/dist/* deploy/

        # 复制子应用的 remoteEntry.js 和静态资源到子目录
        # 但不复制子应用的 index.html，避免直接访问
        mkdir -p deploy/mf-counter
        cp counter/dist/remoteEntry.js deploy/mf-counter/
        cp -r counter/dist/static deploy/mf-counter/ 2>/dev/null || true
        cp -r counter/dist/mf-* deploy/mf-counter/ 2>/dev/null || true

        mkdir -p deploy/mf-todos
        cp todos/dist/remoteEntry.js deploy/mf-todos/
        cp -r todos/dist/static deploy/mf-todos/ 2>/dev/null || true
        cp -r todos/dist/mf-* deploy/mf-todos/ 2>/dev/null || true

        # 设置 GitHub Pages 配置
        cd deploy
        touch .nojekyll
        echo "# 微前端演示平台" > README.md
        echo "基于 Module Federation 的微前端架构演示" >> README.md
        # 创建 404.html 用于 SPA 路由重定向
        cp index.html 404.html

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4